# Generated by Django 3.2.3 on 2021-07-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_product_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='item_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='item_status',
        ),
    ]
